### ISSUE TITLE
I do not know if I omit anything that is necessary for the packaging process.

### ISSUE THREAD

**Issue by zenaway** [electron-userland/electron-installer-windows#245]
**What version of `electron-installer-windows` are you using?**
1.1.0
**What version of `node` and `npm` are you using?**
6.1.0
**What operating system are you using?**
Windows 10 1803
**Can you compile the [example app](https://github.com/electron-userland/electron-installer-windows/tree/master/example) successfully?**
yes!
**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/electron-userland/electron-installer-windows.git
$ cd electron-installer-windows/example
$ DEBUG='electron-installer-windows' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
{
    "icon": "resources/icon.ico",
    "animation": "resources/on.gif",
    "tags": ["Utility"],
    "remoteReleases" : "https://github.com/myGithubId/myAppName"
}

**What did you expect to happen?**
Successful packaging
**What actually happened?**
Error: Error syncing remote releases: Error executing command (Cannot read property \'toString\' of null)

I just added the remoteReleases address and I did not finish the packaging due to an error during the packaging process. Please let us know if there is a configuration field that you need to add in addition to the address, or if there is anything you need to do. I just want to add the automatic update content to the packaging.

**Comment by fcastilloec** [comment]
You didn't output any logs using `DEBUG='electron-installer-windows'` so it's hard to know your problem but given your configuration, your problem is that your remote release server is not working. Please read very carefully the README, specially [`options.remoteReleases`](https://github.com/electron-userland/electron-installer-windows#optionsremotereleases) to see what it does, how it works, and what do you need if you want to use Github.

I'm going to close this because it's not an issue with this module.
