### ISSUE TITLE
Document expected install destination?

### ISSUE THREAD

**Issue by axfelix** [electron-userland/electron-installer-windows#256]
**What version of `electron-installer-windows` are you using?**
Most recent

**What version of `node` and `npm` are you using?**
6.5.0

**What operating system are you using?**
Windows 10

**Can you compile the [example app](https://github.com/electron-userland/electron-installer-windows/tree/master/example) successfully?**
Yes

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
Ran an MSI installer generated by `electron-installer-windows`

**What did you expect to happen?**
Shortcuts to be generated and the application to be installed at a predictable destination.

**What actually happened?**
I'm not sure -- I'm not able to find any shortcuts or executables for my application when searching via the start menu (except for in my development directory), and there's no documentation as to where it should've been installed, so I'm not sure what the expected behaviour is.

**Comment by fcastilloec** [comment]
You should read the Squirrel documentation since that's what we use:
https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/machine-wide-installs.md
Which brings me to this: "Have you tried turning off and on again?" :smile: MSI will install on the user's next login.

I haven't tested a msi installer since we moved to `electron-installer-common` but everything should work as excepted. You should try the `exe` first. Any errors when installing, regarding shortcuts and such, are usually due to your configuration and/or your app itself.

**Comment by axfelix** [comment]
Thanks! I got nothing from the MSI even after logging out and in again, uninstalled it, installed via the .exe, and am now getting a working install to %LOCALAPPDATA% but no shortcuts. It's not clear to me from the Squirrel documentation what I'd be missing in order to get shortcuts generated...

**Comment by fcastilloec** [comment]
I think the best place is to read https://docs.microsoft.com/en-us/nuget/reference/nuspec
Squirrel uses the nuspec file to generate the installer, we support the majority of those options. You could have found this site by clicking in any of the options in our README, which I encorage you to read thoroughly.

You probably need `options.iconUrl` otherwise there's no way a shortcut can be created if there's no icon. You should also consider using `options.icon` so you can change the icon of your `exe`

**Comment by axfelix** [comment]
Thanks again -- and sorry for asking questions based on publicly available documentation, I'm just not familiar with the Squirrel ecosystem and it wasn't intuitive to get there from here.

This open issue also suggests the requirements are unclear and that it's possible to provide these in the electron package.json under build.squirrelWindows (rather than supplying a separate XML file per the Microsoft documentation), but it sounds like your preferred method is with a separate config.json passed to the build script?

I'm finding that if I create `resources/icon.ico`, which seems to be the default per the spec without needing to pass `options.icon`, I'm still not getting a shortcut created on install.

**Comment by fcastilloec** [comment]
@axfelix you need to read only our documentation, the whole README, if you're going to use our tool. Reading the nuspec is also very helpful, and that's why many of the options in our README have a link to the nuspec specification.
Issues from other tools (like electron-builder) don't apply to this module.

There's really just one way to pass arguments to this module, and it's by using a `json` configuration file. You could also pass them on the command line, but nobody does that unless you don't really have any configuration options (also stated in our README). XML files and other ways don't apply to this tool, otherwise we would have mentioned that on the README. This tool relies on Squirrel, but automates the process, so you don't have to create XML files or anything of that sorts.

As I previously mentioned:
> You probably need `options.iconUrl` otherwise there's no way a shortcut can be created if there's no icon. You should also consider using `options.icon` so you can change the icon of your `exe`

The `iconUrl` is a URL, not a file, as per the name, the description in our README and the [nuspec specification](https://docs.microsoft.com/en-us/nuget/reference/nuspec#iconurl).

Quoting our README regarding the `options.icon`:
> `options.icon` The path to an .ico file used for the generated .exe installer.

This is only for changing the icon of the installer, the `exe`, which I previously mentioned. This will not add an icon to your shortcuts, but it's a good idea to do so you're installer has a personalinze icon to differentiate it from other installers.
