### ISSUE TITLE
empty setup.exe

### ISSUE THREAD

**Issue by andreineculau** [electron-userland/electron-installer-windows#271]
**What version of `electron-installer-windows` are you using?**
1.1.1

replacing node_modules/electron-installer-windows/vendor/squirrel/signtool.exe
with https://github.com/dustinblackman/mono-signtool

**What version of `node` and `npm` are you using?**
node v11.14.0
npm v6.9.0

**What operating system are you using?**

macos 10.14.4

**Can you compile the [example app](https://github.com/electron-userland/electron-installer-windows/tree/master/example) successfully?**

Yes, except I had to change the "author" field in package.json to a string.

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/electron-userland/electron-installer-windows.git
$ cd electron-installer-windows/example
$ DEBUG='electron-installer-windows' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**

no config, just passing `--src`, `--dest` and certificates via `--certificateFile` and `--certificatePassword`

**What did you expect to happen?**

to get out 3 artifacts: RELEASES, name-version-full.nupkg and name-version-setup.exe

**What actually happened?**

I am getting name-version-setup.exe as a zero-byte file. This happens on and off, with the mention that usually running the same command again, will actually produce a proper exe, as if having my environment "contaminated" by the first run of "electron-installer-windows" fixes smth 🤷‍♂️ 

I have run with `DEBUG=electron-installer-windows` but everything looks identical.
I have also taken a look at the contents of the staging folder while the setup.exe was being generated and things looks fine there as well, with ok sizes between a staging dir of a non-zero setup.exe and a staging dir of a zero setup.exe.

Any help is tremendously appreciated.

**Comment by fcastilloec** [comment]
It seems the problem your having is with the signtool you replaced. I have not been able to reproduce this in Windows, all `.exe` are non-zero. We don't support signing on Linux/macOS because Squirrel doesn't support it. Building without signing on Linux and macOS doesn't have any problem.
I suggest you report this back to the signtool you're using rather than here.

As a suggestion, maybe you could use a Windows virtual-machine to test your code. You can also use a CI to build and test your code.
I use Linux, so in my other project ([headset](https://github.com/headsetapp/headset-electron)) we use Appveyor to build, test and sign our packages
