### ISSUE TITLE
Example error, cant compile 

### ISSUE THREAD

**Issue by LittleHamster** [electron-userland/electron-installer-windows#314]
I can't seem to compile the example 

**What version of `node` and `npm` are you using?**
npm 6.13.6 / node v10.11.0

**What operating system are you using?**
Mac

**What actually happened?**

```
Packaging app for platform win32 ia32 using electron v7.1.13
Could not find "wine64" on your system.

Wine is required to use the appCopyright, appVersion, buildVersion, icon, and 
win32metadata parameters for Windows targets.

Make sure that the "wine64" executable is in your PATH.
```

**Comment by fcastilloec** [comment]
The error you're getting is self-explanatory. You are missing `wine64` in your system.
Also, we have a list of [requirements](https://github.com/electron-userland/electron-installer-windows#requirements) on the top of our README.

**Comment by fcastilloec** [comment]
I notice that the error was asking for `wine64`, this might be related to Squirrel.Windows which is the tool that all the electron projects use to make a distributable and macOS Catalina. Squirrel.Windows hasn't seen any releases since last year and it's looking for a maintainer, so I doubt we'll see a fix soon.
I think the best way to build a Windows app on macOS right now is to use a Windows VM. You could also use a Linux VM since Linux doesn't have this problem; but if you're using a VM, you might as well use Windows. You don't even need a Windows license since it's free for a couple of days.
You could also use Docker with a Linux image as an alternative.
