### ISSUE TITLE
Unable to make msi file

### ISSUE THREAD

**Issue by YeetOrBeYate** [electron-userland/electron-installer-windows#337]
**What version of `electron-installer-windows` are you using?**

"electron-installer-windows": "^3.0.0"

**What version of `node` and `npm` are you using?**

NPM: 6.14.9

Yarn: v1.22.4

**What operating system are you using?**

Windows

**Can you compile the [example app](https://github.com/electron-userland/electron-installer-windows/tree/master/example) successfully?**

Yes

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**

I used this script in my package.json to create installer files

`    "create-installer-win": "electron-installer-windows --src release-builds/electron-tutorial-app-win32-ia32/ --exe electron-tutorial-app.exe --icon assets/app.ico --noMsi=false  --dest dist/installers/"
`
**What did you expect to happen?**

I thought It would make an msi file but the only files present in the dist/installers are .nupkg and .exe. 

I need an msi file, anyone know why following the docs wouldn't give me an msi?

**What actually happened?**

**Comment by fcastilloec** [comment]
If you can compile the example app successfully and you can generate a msi with the example app (which you said you can), there's no issue with the module.
If you read the README carefully, you'll realize that by default we always create a msi installer. Your problem is that `--noMsi` is boolean, which means that by calling the argument (`--noMsi`), you're telling the system to set it to `true`. It doesn't matter that you added `=false`, that would work if it wasn't a boolean option that needs a string.
This behavior comes from `yargs` which is what we use to implement the command line and the only way to negate a boolean would be to pass `--no-noMsi`, this will set it as `false`. Anyway, this is all not necessary since I originally mentioned that we set it as `false` by default.

I highly suggest you create a `config.json` file, where you can easily and unambiguously pass all the options that you want. Based on you're description, the file can look like this:

```json
{
  "src": "release-builds/electron-tutorial-app-win32-ia32",
  "dest": "dist/installers",
  "exe": "electron-tutorial-app.exe",
  "icon": "assets/app.ico",
  "noMsi": false
}
```

And your `package.json` script should look like this: `"create-installer-win": "electron-installer-windows --config config.json"`
This way you can make changes to how you build your windows installer without having to make changes to your `package.json`
